### ISSUE TITLE
Package Solarus Quest Editor (C++) for Debian 8 32 and 64 bit

### ISSUE THREAD

**Issue by Nate-Devv** [Nate-Devv/apt#2]
With the introduction of the C++ Quest Editor, a Debian package can easily be made.

**Comment by Nate-Devv** [comment]
Looks like the C++ Quest Editor is for Solarus 1.4? @christopho
If that is the case, I will package it with the release of Solarus 1.4.

**Comment by christopho** [comment]
Yes, exactly :)

**Comment by Nate-Devv** [comment]
OK.

**Comment by Nate-Devv** [comment]
The fix proposed on the comments of 582c6a3caebed48621a58ab38d64018a02537fc4: Add the package qttools5-dev to the packages installed for building works @christopho.  All I need to know is which commit for the editor is the right one.  The tag for 1.4.2 creates a 1.5 editor, and there were some crucial changes made (or so it seems) from the 1.4.1 tagged release of the editor to what should be the 1.4.2 release of the editor.

**Comment by christopho** [comment]
For the editor, the tag v1.4.2 is the correct one: (commit https://github.com/christopho/solarus-quest-editor/commit/991c307a53550dfd2f65c4fd7724a5060f407d6d).

You have to compile the editor with an installation of Solarus 1.4, from the tag v1.4.2-correctcommit (commit https://github.com/christopho/solarus/commit/e3d6e6e344ab49221e5ed2471b2ba8736e3cc011)

Maybe you compiled Solarus Quest Editor 1.4 with Solarus 1.5 and this explains why you see an 1.5 editor. (In future releases this will be checked to avoid errors.)

**Comment by Nate-Devv** [comment]
OK cool, I had the faulty solarus "1.4.2" package installed.  The changelog said that the 1.5 version was in progress,  so I assumed that you had the wrong editor source.  My bad!
